server:
  address: localhost
  port: 8080
  servlet:
    context-path: /pp
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: never
    path: /error
    whitelabel:
      enabled: false

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 200KB
      max-file-size: 150MB
      max-request-size: 150MB
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /views
      suffix: .jsp
  jmx:
    enabled: false
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://127.0.0.1:5432/drugsafe?tcpKeepAlive=true&connectTimeout=10&socketTimeout=600
    username: drugsafe
    password: 7mw8kw8mw7kw
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 5
      connection-test-query: SELECT 1
  path:
    fileUploadDir: /inusquare/upload
    urlFilePath: /
    evdnDocFileUploadDir: /resources/doc
  web:
    resources:
      add-mappings: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password   # Gmail 앱 비밀번호
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

springdoc:
  swagger-ui:
#    doc-expansion: full           # API 목록 접힘 (선택)
    default-model-expand-depth: 5
    default-models-expand-depth: 5

file:
  storePath: C:\data
  url: /files

logging:
  level:
    kr.go.kids.domain: DEBUG
    jdbc.sqltiming: INFO
    jdbc.resultsettable: INFO

mybatis:
  type-aliases-package: kr.go.kids.domain
  mapper-locations: mybatis/postgresql/mapper/**/*.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: WARNING
    default-executor-type: simple
    default-statement-timeout: 30
    default-fetch-size: 100
    safe-row-bounds-enabled: false
    map-underscore-to-camel-case: true
    local-cache-scope: session
    jdbc-type-for-null: NULL