server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: never
    path: /error
    whitelabel:
      enabled: false

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: drugsafe123456
    timeout: 2000ms
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 200KB
      max-file-size: 150MB
      max-request-size: 150MB
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /views
      suffix: .jsp
  jmx:
    enabled: false
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://192.168.12.146:5432/kids_db?tcpKeepAlive=true&connectTimeout=10&socketTimeout=600
    username: pp_dev
    password: pp_dev
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 5
      connection-test-query: SELECT 1
  path:
    fileUploadDir: /data/upload
    urlFilePath: /
    evdnDocFileUploadDir: /resources/doc
  web:
    resources:
      add-mappings: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  issuer: kids_user
  secret-key: ZGQtaW90LXBjd2ViLWFwaS1hZG1pbi1zZWNyZXRrZXk=
  access-token-expiration: 1800000        # 30분 (ms), ex) 7 * 24 * 60 * 60 * 1000 -> 7일
  refresh-token-expiration: 1209600000   # 14일 (ms), ex) 365 * 24 * 60 * 60 * 1000 -> 365일
  refresh-token-name: KIDS_REFRESH_TOKEN
  idle-timeout-millis: 1800000  # 30분

springdoc:
  swagger-ui:
#    doc-expansion: full           # API 목록 접힘 (선택)
    default-model-expand-depth: 5
    default-models-expand-depth: 5

file:
  storePath: C:\data
  url: /files

logging:
  level:
    kr.go.kids.domain: DEBUG
    jdbc.sqltiming: INFO
    jdbc.resultsettable: INFO
    org.springframework.boot.context.config: DEBUG

mybatis:
  type-aliases-package: kr.go.kids.domain
  mapper-locations: mybatis/postgresql/mapper/**/*.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: WARNING
    default-executor-type: simple
    default-statement-timeout: 30
    default-fetch-size: 100
    safe-row-bounds-enabled: false
    map-underscore-to-camel-case: true
    local-cache-scope: session
    jdbc-type-for-null: NULL